[workspace]
release = true
publish = true
git_tag_enable = true
git_release_enable = false
changelog_update = true
allow_dirty = false
semver_check = true

[[package]]
name = "crustywad"
release = true
publish = true
changelog_path = "crates/crustywad/CHANGELOG.md"

[[package]]
name = "crustywad-cli"
release = true
publish = true
changelog_path = "crates/crustywad-cli/CHANGELOG.md"
