[book]
title = "crustywad"
description = "A safe Rust library for Doom WAD file I/O"
authors = ["Amir Masri"]
language = "en"
src = "src"

[build]
build-dir = "../../target/book"

[output.html]
site-url = "/"
git-repository-url = "https://github.com/masriamir/crustywad"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
