[package]
name = "crustywad"
version = "0.4.0"
description.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

autobenches = false

[lib]
bench = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.dist]
dist = false

[features]
default = []
mmap = ["dep:memmap2"]
freedoom-tests = []
hexen-tests = []
doom64-tests = []
sweep-tests = []
write = []

[dependencies]
binrw.workspace = true
memmap2 = { version = "0.9.5", optional = true }
thiserror.workspace = true

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
proptest.workspace = true
tempfile.workspace = true

[[example]]
name = "write_wad"
required-features = ["write"]

[[bench]]
name = "read_ops"
harness = false

[[bench]]
name = "write_ops"
harness = false
required-features = ["write"]

[lints]
workspace = true
