[package]
name = "crustywad-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "cwad"
path = "src/main.rs"

[features]
default = []
mmap = ["crustywad/mmap"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
crustywad = { path = "../crustywad", version = "0.1.0" }

[lints]
workspace = true
